export interface InsuranceBrandTheme {
  id: string;
  name: string;
  shortName: string;
  fullName: string;
  tagline: string;
  monogram: string;
  defaultBranch: string;
  primaryColor: string; // hex
  primaryHover: string;
  secondaryColor: string;
  lightBg: string;
  badgeBg: string;
  badgeText: string;
  gradientFrom: string;
  gradientTo: string;
  // Tailwind class mappings for seamless dynamic styling
  classes: {
    primaryBg: string;
    primaryBgHover: string;
    primaryText: string;
    primaryBorder: string;
    primaryLightBg: string;
    primaryRing: string;
    primaryShadow: string;
    activeNav: string;
    sidebarBadge: string;
    brandMonogramBg: string;
    brandPillBg: string;
    brandPillText: string;
    statCardIconBg: string;
    statCardIconText: string;
    metricBorderHover: string;
  };
}

export type AppearanceMode = 'clean_light' | 'executive_dark' | 'vibrant_contrast';

export const PHILIPPINE_INSURANCE_BRANDS: InsuranceBrandTheme[] = [
  {
    id: 'inlife',
    name: 'InLife',
    shortName: 'InLife',
    fullName: 'Insular Life Assurance Co., Ltd.',
    tagline: 'A Lifetime for Good',
    monogram: 'IN',
    defaultBranch: 'InLife Makati Financial Center',
    primaryColor: '#00529B',
    primaryHover: '#003E75',
    secondaryColor: '#002244',
    lightBg: '#EFF6FF',
    badgeBg: '#DBEAFE',
    badgeText: '#1E40AF',
    gradientFrom: '#00529B',
    gradientTo: '#0284C7',
    classes: {
      primaryBg: 'bg-blue-600',
      primaryBgHover: 'hover:bg-blue-700',
      primaryText: 'text-blue-600',
      primaryBorder: 'border-blue-200',
      primaryLightBg: 'bg-blue-50',
      primaryRing: 'focus:ring-blue-600',
      primaryShadow: 'shadow-blue-700/25',
      activeNav: 'bg-blue-600 text-white shadow-md shadow-blue-700/25',
      sidebarBadge: 'bg-blue-600/30 text-blue-300',
      brandMonogramBg: 'bg-gradient-to-br from-blue-700 to-indigo-950 shadow-blue-950/30',
      brandPillBg: 'bg-blue-600/30',
      brandPillText: 'text-blue-300',
      statCardIconBg: 'bg-blue-50',
      statCardIconText: 'text-blue-600',
      metricBorderHover: 'hover:border-blue-300',
    },
  },
  {
    id: 'sunlife',
    name: 'Sun Life',
    shortName: 'Sun Life',
    fullName: 'Sun Life of Canada (Philippines), Inc.',
    tagline: "Life's Brighter Under the Sun",
    monogram: 'SL',
    defaultBranch: 'Sun Life BGC Center, Taguig',
    primaryColor: '#D97706',
    primaryHover: '#B45309',
    secondaryColor: '#1E3A8A',
    lightBg: '#FFFBEB',
    badgeBg: '#FEF3C7',
    badgeText: '#92400E',
    gradientFrom: '#F59E0B',
    gradientTo: '#D97706',
    classes: {
      primaryBg: 'bg-amber-500',
      primaryBgHover: 'hover:bg-amber-600',
      primaryText: 'text-amber-600',
      primaryBorder: 'border-amber-200',
      primaryLightBg: 'bg-amber-50',
      primaryRing: 'focus:ring-amber-500',
      primaryShadow: 'shadow-amber-600/25',
      activeNav: 'bg-amber-500 text-slate-950 font-bold shadow-md shadow-amber-600/25',
      sidebarBadge: 'bg-amber-500/30 text-amber-300',
      brandMonogramBg: 'bg-gradient-to-br from-amber-400 to-amber-600 shadow-amber-900/30 text-slate-950',
      brandPillBg: 'bg-amber-500/30',
      brandPillText: 'text-amber-300',
      statCardIconBg: 'bg-amber-50',
      statCardIconText: 'text-amber-600',
      metricBorderHover: 'hover:border-amber-300',
    },
  },
  {
    id: 'prulife',
    name: 'Pru Life UK',
    shortName: 'Pru Life',
    fullName: 'Pru Life Insurance Corp. of U.K.',
    tagline: 'Listening. Understanding. Delivering.',
    monogram: 'PRU',
    defaultBranch: 'Pru Life UK Ortigas Financial Tower',
    primaryColor: '#E11D48',
    primaryHover: '#BE123C',
    secondaryColor: '#881337',
    lightBg: '#FFF1F2',
    badgeBg: '#FFE4E6',
    badgeText: '#9F1239',
    gradientFrom: '#E11D48',
    gradientTo: '#9F1239',
    classes: {
      primaryBg: 'bg-rose-600',
      primaryBgHover: 'hover:bg-rose-700',
      primaryText: 'text-rose-600',
      primaryBorder: 'border-rose-200',
      primaryLightBg: 'bg-rose-50',
      primaryRing: 'focus:ring-rose-600',
      primaryShadow: 'shadow-rose-700/25',
      activeNav: 'bg-rose-600 text-white shadow-md shadow-rose-700/25',
      sidebarBadge: 'bg-rose-600/30 text-rose-400',
      brandMonogramBg: 'bg-gradient-to-br from-rose-600 to-rose-900 shadow-rose-900/30',
      brandPillBg: 'bg-rose-600/30',
      brandPillText: 'text-rose-400',
      statCardIconBg: 'bg-rose-50',
      statCardIconText: 'text-rose-600',
      metricBorderHover: 'hover:border-rose-300',
    },
  },
  {
    id: 'aia',
    name: 'AIA Philippines',
    shortName: 'AIA',
    fullName: 'AIA Philippines Life & General Insurance',
    tagline: 'Healthier, Longer, Better Lives',
    monogram: 'AIA',
    defaultBranch: 'AIA BGC Corporate Center, Taguig',
    primaryColor: '#D31145',
    primaryHover: '#A80C36',
    secondaryColor: '#881337',
    lightBg: '#FFF1F2',
    badgeBg: '#FFE4E6',
    badgeText: '#881337',
    gradientFrom: '#D31145',
    gradientTo: '#881337',
    classes: {
      primaryBg: 'bg-pink-600',
      primaryBgHover: 'hover:bg-pink-700',
      primaryText: 'text-pink-600',
      primaryBorder: 'border-pink-200',
      primaryLightBg: 'bg-pink-50',
      primaryRing: 'focus:ring-pink-600',
      primaryShadow: 'shadow-pink-700/25',
      activeNav: 'bg-pink-600 text-white shadow-md shadow-pink-700/25',
      sidebarBadge: 'bg-pink-600/30 text-pink-400',
      brandMonogramBg: 'bg-gradient-to-br from-pink-600 to-red-900 shadow-pink-900/30',
      brandPillBg: 'bg-pink-600/30',
      brandPillText: 'text-pink-400',
      statCardIconBg: 'bg-pink-50',
      statCardIconText: 'text-pink-600',
      metricBorderHover: 'hover:border-pink-300',
    },
  },
  {
    id: 'manulife',
    name: 'Manulife Philippines',
    shortName: 'Manulife',
    fullName: 'The Manufacturers Life Insurance Co. (Phils.), Inc.',
    tagline: 'Decisions Made Easier. Lives Made Better.',
    monogram: 'ML',
    defaultBranch: 'Manulife Financial Center Makati',
    primaryColor: '#059669',
    primaryHover: '#047857',
    secondaryColor: '#064E3B',
    lightBg: '#ECFDF5',
    badgeBg: '#D1FAE5',
    badgeText: '#065F46',
    gradientFrom: '#10B981',
    gradientTo: '#047857',
    classes: {
      primaryBg: 'bg-emerald-600',
      primaryBgHover: 'hover:bg-emerald-700',
      primaryText: 'text-emerald-600',
      primaryBorder: 'border-emerald-200',
      primaryLightBg: 'bg-emerald-50',
      primaryRing: 'focus:ring-emerald-600',
      primaryShadow: 'shadow-emerald-700/25',
      activeNav: 'bg-emerald-600 text-white shadow-md shadow-emerald-700/25',
      sidebarBadge: 'bg-emerald-600/30 text-emerald-400',
      brandMonogramBg: 'bg-gradient-to-br from-emerald-500 to-teal-800 shadow-emerald-900/30',
      brandPillBg: 'bg-emerald-600/30',
      brandPillText: 'text-emerald-400',
      statCardIconBg: 'bg-emerald-50',
      statCardIconText: 'text-emerald-600',
      metricBorderHover: 'hover:border-emerald-300',
    },
  },
  {
    id: 'fwd',
    name: 'FWD Life Philippines',
    shortName: 'FWD Life',
    fullName: 'FWD Life Insurance Corporation',
    tagline: 'Celebrate Living',
    monogram: 'FWD',
    defaultBranch: 'FWD Financial Plaza, Bonifacio Global City',
    primaryColor: '#EA580C',
    primaryHover: '#C2410C',
    secondaryColor: '#7C2D12',
    lightBg: '#FFF7ED',
    badgeBg: '#FFEDD5',
    badgeText: '#9A3412',
    gradientFrom: '#F97316',
    gradientTo: '#C2410C',
    classes: {
      primaryBg: 'bg-orange-500',
      primaryBgHover: 'hover:bg-orange-600',
      primaryText: 'text-orange-600',
      primaryBorder: 'border-orange-200',
      primaryLightBg: 'bg-orange-50',
      primaryRing: 'focus:ring-orange-500',
      primaryShadow: 'shadow-orange-600/25',
      activeNav: 'bg-orange-500 text-white shadow-md shadow-orange-600/25',
      sidebarBadge: 'bg-orange-500/30 text-orange-400',
      brandMonogramBg: 'bg-gradient-to-br from-orange-500 to-amber-700 shadow-orange-900/30',
      brandPillBg: 'bg-orange-500/30',
      brandPillText: 'text-orange-400',
      statCardIconBg: 'bg-orange-50',
      statCardIconText: 'text-orange-600',
      metricBorderHover: 'hover:border-orange-300',
    },
  },
  {
    id: 'axa',
    name: 'AXA Philippines',
    shortName: 'AXA',
    fullName: 'Philippine AXA Life Insurance Corp. (Metrobank Group)',
    tagline: 'Know You Can',
    monogram: 'AXA',
    defaultBranch: 'AXA Life Center Sen. Gil Puyat Makati',
    primaryColor: '#2563EB',
    primaryHover: '#1D4ED8',
    secondaryColor: '#1E3A8A',
    lightBg: '#EFF6FF',
    badgeBg: '#DBEAFE',
    badgeText: '#1E40AF',
    gradientFrom: '#2563EB',
    gradientTo: '#1E3A8A',
    classes: {
      primaryBg: 'bg-blue-600',
      primaryBgHover: 'hover:bg-blue-700',
      primaryText: 'text-blue-600',
      primaryBorder: 'border-blue-200',
      primaryLightBg: 'bg-blue-50',
      primaryRing: 'focus:ring-blue-600',
      primaryShadow: 'shadow-blue-700/25',
      activeNav: 'bg-blue-600 text-white shadow-md shadow-blue-700/25',
      sidebarBadge: 'bg-blue-600/30 text-blue-400',
      brandMonogramBg: 'bg-gradient-to-br from-blue-600 to-indigo-900 shadow-blue-900/30',
      brandPillBg: 'bg-blue-600/30',
      brandPillText: 'text-blue-400',
      statCardIconBg: 'bg-blue-50',
      statCardIconText: 'text-blue-600',
      metricBorderHover: 'hover:border-blue-300',
    },
  },
  {
    id: 'allianz',
    name: 'Allianz PNB Life',
    shortName: 'Allianz PNB',
    fullName: 'Allianz PNB Life Insurance, Inc.',
    tagline: 'Confidence in Tomorrow',
    monogram: 'ALZ',
    defaultBranch: 'Allianz PNB Center Ayala Ave Makati',
    primaryColor: '#0284C7',
    primaryHover: '#0369A1',
    secondaryColor: '#0C4A6E',
    lightBg: '#F0F9FF',
    badgeBg: '#E0F2FE',
    badgeText: '#075985',
    gradientFrom: '#0284C7',
    gradientTo: '#0C4A6E',
    classes: {
      primaryBg: 'bg-sky-600',
      primaryBgHover: 'hover:bg-sky-700',
      primaryText: 'text-sky-600',
      primaryBorder: 'border-sky-200',
      primaryLightBg: 'bg-sky-50',
      primaryRing: 'focus:ring-sky-600',
      primaryShadow: 'shadow-sky-700/25',
      activeNav: 'bg-sky-600 text-white shadow-md shadow-sky-700/25',
      sidebarBadge: 'bg-sky-600/30 text-sky-400',
      brandMonogramBg: 'bg-gradient-to-br from-sky-600 to-indigo-900 shadow-sky-900/30',
      brandPillBg: 'bg-sky-600/30',
      brandPillText: 'text-sky-400',
      statCardIconBg: 'bg-sky-50',
      statCardIconText: 'text-sky-600',
      metricBorderHover: 'hover:border-sky-300',
    },
  },
  {
    id: 'bpiaia',
    name: 'BPI-AIA Life',
    shortName: 'BPI-AIA',
    fullName: 'BPI-AIA Life Assurance Corp. (formerly BPI-Philam)',
    tagline: 'Making Insurance Easy',
    monogram: 'BPI',
    defaultBranch: 'BPI-AIA Life Head Office Makati',
    primaryColor: '#881337',
    primaryHover: '#700D2B',
    secondaryColor: '#4C0519',
    lightBg: '#FFF1F2',
    badgeBg: '#FFE4E6',
    badgeText: '#881337',
    gradientFrom: '#881337',
    gradientTo: '#4C0519',
    classes: {
      primaryBg: 'bg-rose-900',
      primaryBgHover: 'hover:bg-rose-950',
      primaryText: 'text-rose-900',
      primaryBorder: 'border-rose-200',
      primaryLightBg: 'bg-rose-50',
      primaryRing: 'focus:ring-rose-900',
      primaryShadow: 'shadow-rose-950/25',
      activeNav: 'bg-rose-900 text-white shadow-md shadow-rose-950/25',
      sidebarBadge: 'bg-rose-900/30 text-rose-300',
      brandMonogramBg: 'bg-gradient-to-br from-rose-900 to-red-950 shadow-rose-950/30',
      brandPillBg: 'bg-rose-900/30',
      brandPillText: 'text-rose-300',
      statCardIconBg: 'bg-rose-50',
      statCardIconText: 'text-rose-900',
      metricBorderHover: 'hover:border-rose-300',
    },
  },
  {
    id: 'singlife',
    name: 'Singlife Philippines',
    shortName: 'Singlife',
    fullName: 'Singlife Philippines, Inc.',
    tagline: 'Money for What Matters',
    monogram: 'SLP',
    defaultBranch: 'Singlife Digital Hub BGC',
    primaryColor: '#0D9488',
    primaryHover: '#0F766E',
    secondaryColor: '#115E59',
    lightBg: '#F0FDFA',
    badgeBg: '#CCFBF1',
    badgeText: '#115E59',
    gradientFrom: '#14B8A6',
    gradientTo: '#0F766E',
    classes: {
      primaryBg: 'bg-teal-600',
      primaryBgHover: 'hover:bg-teal-700',
      primaryText: 'text-teal-600',
      primaryBorder: 'border-teal-200',
      primaryLightBg: 'bg-teal-50',
      primaryRing: 'focus:ring-teal-600',
      primaryShadow: 'shadow-teal-700/25',
      activeNav: 'bg-teal-600 text-white shadow-md shadow-teal-700/25',
      sidebarBadge: 'bg-teal-600/30 text-teal-300',
      brandMonogramBg: 'bg-gradient-to-br from-teal-500 to-emerald-800 shadow-teal-900/30',
      brandPillBg: 'bg-teal-600/30',
      brandPillText: 'text-teal-300',
      statCardIconBg: 'bg-teal-50',
      statCardIconText: 'text-teal-600',
      metricBorderHover: 'hover:border-teal-300',
    },
  },
];
